### ISSUE TITLE
Test failures with older gmp versions

### ISSUE THREAD

**Issue by eserte** [trizen/Math-AnyNum#1]
See https://rt.cpan.org/Ticket/Display.html?id=120910

**Comment by trizen** [comment]
Thanks. Version 0.03 has been released, which includes a quick workaround for this issue. (see https://github.com/trizen/Math-AnyNum/commit/65562ffd28dbd806863dab21d7f0f2f82a23a0a5#diff-a142a6c47c71d529608520e181005eba)

**Comment by eserte** [comment]
Actually I see still failures with 0.03 and gmp5:
```
Rmpz_primorial_ui not implemented - gmp-5.1.0 (or later) is needed at /home/cpansand/.cpan/build/2017040818/Math-AnyNum-0.03-0/blib/lib/Math/AnyNum.pm line 2940.
# Looks like your test exited with 255 just after 47.
t/integer_operations.t ....... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 20/67 subtests 
```

**Comment by trizen** [comment]
Before version 0.04 is released, would you like to test the latest commit against gmp<5.1.0 to check if everything is OK? Thanks!

**Comment by eserte** [comment]
Yes, the gmp5 issue is resolved (tried commit e92e9659f0e2463b63b0e2938f4c85efeaef2e58).
However, there are still issues with mpc (`mpc_log10 not implemented until mpc-1.0. We have version 2304`).

**Comment by trizen** [comment]
That's good news. Thank you very much for testing!

Regarding the `mpc_log10()` issue, a workaround has been committed [here](https://github.com/trizen/Math-AnyNum/commit/86572910eb6fd9f45c4f15d8b2bd388b5c8ed272).

**Comment by eserte** [comment]
It's getting better. With commit 86572910eb6fd9f45c4f15d8b2bd388b5c8ed272 only one test file is failing:
```
t/integer_functions.t ........ Failed 125/218 subtests
        (less 11 skipped subtests: 82 okay)
```
With detailed tests:
```
ok 93
[1]    24349 floating point exception  perl5.24.0 -T -Mblib t/integer_functions.t
```

**Comment by trizen** [comment]
Please test the latest commit.

**Comment by eserte** [comment]
Perfect!

**Comment by trizen** [comment]
Awesome! Thank you very much for your time. Version 0.04 will be released soon.

**Comment by eserte** [comment]
There are no more problems with 0.04: http://fast-matrix.cpantesters.org/?dist=Math-AnyNum%200.04
